language: php

php:
  - 7.1
  - 7.2

env:
  - COMPOSER_OPTS="--prefer-lowest"
  - COMPOSER_OPTS=""

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script:
  - vendor/bin/simple-phpunit

notifications:
  email: info@endroid.nl
