language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  - COMPOSER_OPTS="--prefer-lowest"
  - COMPOSER_OPTS=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

notifications:
  email: info@endroid.nl
