language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"

before_install:
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi
  - phpenv config-rm xdebug.ini

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit

notifications:
  email: info@endroid.nl
