services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Endroid\QrCode\Factory\QrCodeFactory:
        $defaultOptions: [ ]

    Endroid\QrCode\WriterRegistryInterface: '@Endroid\QrCode\WriterRegistry'
    Endroid\QrCode\Factory\QrCodeFactoryInterface: '@Endroid\QrCode\Factory\QrCodeFactory'

    Endroid\QrCode\Twig\Extension\QrCodeExtension: ~
    Endroid\QrCode\WriterRegistry: ~

    _instanceof:
        Endroid\QrCode\Writer\WriterInterface:
            tags: [ endroid.qrcode.writer ]
