services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Endroid\QrCode\Writer\WriterInterface:
            tags: ['endroid.qr_code.writer']

    Endroid\QrCode\WriterRegistryInterface: '@Endroid\QrCode\WriterRegistry'
    Endroid\QrCode\WriterRegistry: ~

    Endroid\QrCode\Factory\QrCodeFactoryInterface: '@Endroid\QrCode\Factory\QrCodeFactory'
    Endroid\QrCode\Factory\QrCodeFactory:
        arguments:
            $defaultOptions: [ ]
        public: true

    Endroid\QrCode\Twig\Extension\QrCodeUriExtension:
        public: true
        arguments:
            - '@Endroid\QrCode\Factory\QrCodeFactory'

    Endroid\QrCode\Writer\BinaryWriter: ~
    Endroid\QrCode\Writer\DebugWriter: ~
    Endroid\QrCode\Writer\EpsWriter: ~
    Endroid\QrCode\Writer\PngWriter: ~
    Endroid\QrCode\Writer\SvgWriter: ~
