services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Endroid\QrCode\Factory\QrCodeFactory:
        $defaultOptions: [ ]

    Endroid\QrCode\WriterRegistryInterface: '@Endroid\QrCode\WriterRegistry'
    Endroid\QrCode\Factory\QrCodeFactoryInterface: '@Endroid\QrCode\Factory\QrCodeFactoryInterface'

    Endroid\QrCode\Twig\Extension\QrCodeExtension: ~

    _instanceof:
        Endroid\QrCode\WriterInterface:
            tags: [ endroid.qrcode.writer ]
