services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Endroid\QrCode\Writer\WriterInterface:
            tags: ['endroid.qrcode.writer']

    Endroid\QrCodeBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\QrCode\WriterRegistryInterface: '@Endroid\QrCode\WriterRegistry'
    Endroid\QrCode\WriterRegistry: ~

    Endroid\QrCode\Factory\QrCodeFactoryInterface: '@Endroid\QrCode\Factory\QrCodeFactory'
    Endroid\QrCode\Factory\QrCodeFactory:
        arguments:
            $defaultOptions: [ ]
        public: true

    Endroid\QrCode\Twig\Extension\QrCodeUriExtension:
        public: true
        arguments:
            - '@Endroid\QrCode\Factory\QrCodeFactory'

    Endroid\QrCodeBundle\Twig\QrCodeRoutingExtension:
        public: true
        arguments:
            - '@Endroid\QrCode\Factory\QrCodeFactory'
            - '@router'

    Endroid\QrCode\Writer\BinaryWriter: ~
    Endroid\QrCode\Writer\DebugWriter: ~
    Endroid\QrCode\Writer\EpsWriter: ~
    Endroid\QrCode\Writer\PngWriter: ~
    Endroid\QrCode\Writer\SvgWriter: ~
